apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  namespace: ecommerce-namespace
spec:
  replicas: 1                          # initial replica count; HPA will adjust between 2–5
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce-container
        image: saisamarth21/e-commerce:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000          # internal port only; no hostPort binding
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
