apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  namespace: ecommerce-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce-container
        image: saisamarth21/e-commerce:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000
          hostPort: 2000
          protocol: TCP
        # Optional: resource requests/limits
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
